### ISSUE TITLE
Bad error with no emmitters specified in cadl-project.yaml 

### ISSUE THREAD

**Issue by Petermarcu** [microsoft/typespec#1662]
Cadl compiler v0.37.0

If I have no emmitters specified in my cadl-project.yaml I get this not so helpful error:

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at resolveEmitters (file:///C:/repos/cadl/keyvault/node_modules/@cadl-lang/compiler/dist/core/cli.js:311:55)
    at getCompilerOptions (file:///C:/repos/cadl/keyvault/node_modules/@cadl-lang/compiler/dist/core/cli.js:277:19)
    at async Object.handler (file:///C:/repos/cadl/keyvault/node_modules/@cadl-lang/compiler/dist/core/cli.js:108:28)

**Comment by timotheeguerin** [comment]
I can't seem to repro this, tried with 
- empty `tsconfig.yaml`
- file with just `emitters:`
- file with just `options:`
- file with just `emit:`

Think this probably got fixed, I do remember there was a few issues originally when `emit` and `options` got introduced .


Can reopen a new issue with the problematic tsconfig if this is still happening.
