### ISSUE TITLE
Cannot use 'in' operator to search for 'stack' in No Api-Version Provided

### ISSUE THREAD

**Issue by cataggar** [microsoft/typespec#1894]
Very similar error to #1891 and #1299.  If I remove the ServiceApiVersions, then I get error:

```
PS C:\Users\cataggar\ms\avs\src\conveyor\ConsumptionWorker\client> tsp compile .
TypeSpec compiler v0.43.0

Internal compiler error!
File issue at https://github.com/microsoft/typespec

TypeError: Cannot use 'in' operator to search for 'stack' in No Api-Version Provided
    at runEmitter (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@typespec/compiler/dist/core/program.js:537:25)
    at async compile (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@typespec/compiler/dist/core/program.js:238:9)
    at async Object.handler (file:///C:/Users/cataggar/ms/avs/src/conveyor/ConsumptionWorker/client/node_modules/@typespec/compiler/dist/core/cli/cli.js:118:25)
````

main.tsp
``` tsp
import "@typespec/rest";
import "@typespec/http";
import "@typespec/versioning";

import "./routes.tsp";

using TypeSpec.Rest;
using TypeSpec.Http;
using TypeSpec.Versioning;

@service({
  title: "ConsumptionWorker API",
})

// @versioned(ServiceApiVersions)
namespace ConsumptionWorker;

// enum ServiceApiVersions {
//   v2023_05: "2023-05",
// }
```

**Comment by timotheeguerin** [comment]
which emitter are you using, the emitter seems to be throwing `string` instead of diagnostics

**Comment by cataggar** [comment]
Moved to https://github.com/Azure/autorest.csharp/issues/3348.
