### ISSUE TITLE
Using a decorator that references what it is decorating causes internal compiler error

### ISSUE THREAD

**Issue by johanste** [microsoft/typespec#1940]
The shortest repro:

```typespec
@doc("{name}", boom)
op boom(): void;
```

```
RangeError: Maximum call stack size exceeded at getTypeForNode (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-ee603dbc.js:32055:28) at https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-ee603dbc.js:34116:26 at Array.map (<anonymous>) at checkDecoratorArguments (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-ee603dbc.js:34115:36) at checkDecorator (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-ee603dbc.js:33998:22) at checkDecorators (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-ee603dbc.js:34107:31) at checkOperation (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-ee603dbc.js:32845:28) at checkDeclaredType (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-ee603dbc.js:32452:31) at checkTypeReferenceSymbol (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-ee603dbc.js:32366:32) at checkTypeReference (https://cadlplayground.z22.web.core.windows.net/libs/@typespec/compiler/emitter-utils-ee603dbc.js:32237:22)
```
[Playground](https://cadlplayground.z22.web.core.windows.net/?c=QGRvYygie25hbWV9IiwgYm9vbSkKb3DFCSgpOiB2b2lkOw%3D%3D)

The specific scenario I had was a self-referential custom pagination operation:

```typespec
@nextPageOperation(getNextPage)
op getNextPage(): Page<Item>

@nextPageOperation(getNextPage)
op listStuff(): Page<Item>;
```

**Comment by timotheeguerin** [comment]
is the descision here that it should just work or that this should be an error?

**Comment by timotheeguerin** [comment]
Turns out this already work with model and is an issue only with operation
