### ISSUE TITLE
Importing a folder with a package.json without a `tspMain` crash

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2935]
``` 
TypeSpec compiler v0.53.1

Internal compiler error!
File issue at https://github.com/microsoft/typespec

TypeError: package "undefined" main must be a string but was 'undefined'
    at loadPackage (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/compiler/src/core/module-resolver.ts:217:13)
    at loadAsDirectory (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/compiler/src/core/module-resolver.ts:196:14)
    at resolveModule (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/compiler/src/core/module-resolver.ts:119:43)
    at resolveTypeSpecLibrary (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/compiler/src/core/program.ts:888:14)
    at loadImport (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/compiler/src/core/program.ts:609:21)
    at loadImports (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/compiler/src/core/program.ts:599:7)
    at loadScriptImports (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/compiler/src/core/program.ts:579:5)
    at loadTypeSpecScript (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/compiler/src/core/program.ts:562:5)
    at loadTypeSpecFile (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/compiler/src/core/program.ts:491:7)
    at loadMain (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/compiler/src/core/program.ts:984:16)
```

**Comment by timotheeguerin** [comment]
<img width="966" alt="Image" src="https://github.com/user-attachments/assets/120b682f-e82e-46a0-9937-d4d12bfbec26" />
this has been resolved
