### ISSUE TITLE
[Bug]: Crash when using void or null as body type.

### ISSUE THREAD

**Issue by LadyCailin** [microsoft/typespec#3073]
### Describe the bug

Error: Unknown intrinsic type void
    at OpenAPI3SchemaEmitter.intrinsic (file:///C:/Users/Cailin/OneDrive/Code/CommandHelper/src/main/resources/apps.methodscript.com/node_modules/@typespec/openapi3/dist/src/schema-emitter.js:319:15)
    at file:///C:/Users/Cailin/OneDrive/Code/CommandHelper/src/main/resources/apps.methodscript.com/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:377:55
    at withTypeContext (file:///C:/Users/Cailin/OneDrive/Code/CommandHelper/src/main/resources/apps.methodscript.com/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:520:9)
    at invokeTypeEmitter (file:///C:/Users/Cailin/OneDrive/Code/CommandHelper/src/main/resources/apps.methodscript.com/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:367:9)
    at Object.emitType (file:///C:/Users/Cailin/OneDrive/Code/CommandHelper/src/main/resources/apps.methodscript.com/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:268:28)
    at file:///C:/Users/Cailin/OneDrive/Code/CommandHelper/src/main/resources/apps.methodscript.com/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:160:37
    at withPatchedReferenceContext (file:///C:/Users/Cailin/OneDrive/Code/CommandHelper/src/main/resources/apps.methodscript.com/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:535:28)
    at Object.emitTypeReference (file:///C:/Users/Cailin/OneDrive/Code/CommandHelper/src/main/resources/apps.methodscript.com/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:142:20)
    at OpenAPI3SchemaEmitter.modelPropertyLiteral (file:///C:/Users/Cailin/OneDrive/Code/CommandHelper/src/main/resources/apps.methodscript.com/node_modules/@typespec/openapi3/dist/src/schema-emitter.js:177:40)
    at file:///C:/Users/Cailin/OneDrive/Code/CommandHelper/src/main/resources/apps.methodscript.com/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:377:55

--------------------------------------------------
Library Version                0.54.0
TypeSpec Compiler Version      0.54.0
--------------------------------------------------

### Reproduction

https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQp1c2luZyBUeXBlU3BlYy5IdHRwOw0KDQppbnRlcmZhY2UgZm9vIHsNCiAgQGdldCBiYXIoKTrGESAgYm9keTogdm9pZMQQfQ0KfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
thanks for the nice repro, it he case of what you were trying to do either you want the response to be exactly void or you should add @body on that property. Here it would mean that there is a property in the body of type void which doesn’t make much sense.

the crash nevertheless shouldn’t be happening and we should give you a better error
