### ISSUE TITLE
[Bug]: tsp install breaks on latest version of node

### ISSUE THREAD

**Issue by LadyCailin** [microsoft/typespec#3242]
### Describe the bug

```
> node --version
v20.12.2
> tsp install
TypeSpec compiler v0.53.1

tsp install

Install TypeSpec dependencies

Options:
  --help     Show help                                                 [boolean]
  --debug    Output debug log messages.               [boolean] [default: false]
  --pretty   Enable color and formatting in TypeSpec's output to make compiler e
             rrors easier to read.                     [boolean] [default: true]
  --version  Show version number                                       [boolean]

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at installTypeSpecDependencies (file:///C:/Users/caismith/Code/AD-AggregatorService-Workloads/node_modules/@typespec/compiler/dist/src/core/install.js:4:19)
    at file:///C:/Users/caismith/Code/AD-AggregatorService-Workloads/node_modules/@typespec/compiler/dist/src/core/cli/cli.js:157:95
    at Object.handler (file:///C:/Users/caismith/Code/AD-AggregatorService-Workloads/node_modules/@typespec/compiler/dist/src/core/cli/utils.js:16:16)
    at file:///C:/Users/caismith/Code/AD-AggregatorService-Workloads/node_modules/yargs/build/lib/command.js:206:54
    at maybeAsyncResult (file:///C:/Users/caismith/Code/AD-AggregatorService-Workloads/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)
    at CommandInstance.handleValidationAndGetResult (file:///C:/Users/caismith/Code/AD-AggregatorService-Workloads/node_modules/yargs/build/lib/command.js:205:25)
    at CommandInstance.applyMiddlewareAndGetResult (file:///C:/Users/caismith/Code/AD-AggregatorService-Workloads/node_modules/yargs/build/lib/command.js:245:20)
    at CommandInstance.runCommand (file:///C:/Users/caismith/Code/AD-AggregatorService-Workloads/node_modules/yargs/build/lib/command.js:128:20) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}
```

According to https://github.com/nodejs/node/issues/52554 this is an intentional breakage in the latest version of node.

### Reproduction

1. Download NodeJS Version v18.20.2, v20.12.2, v21.7.3
2. Run `tsp install`

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
yeah we especially were not calling shell: true and having hardcoded mapping of the windows vs linux executable name to we wouldn't have to deal with escaping parameters. I'll investigate if there is a better way or we will need to do that
