### ISSUE TITLE
[Error]: spawn EINVAL -4071

### ISSUE THREAD

**Issue by DarekDan** [microsoft/typespec#3256]
### Describe the bug

While running `tsp install` right after `tsp init` (a new clean project) on Windows 11 (details below) with Node 20.12.2, I am getting the following error:

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at installTypeSpecDependencies (file:///D:/Scratch/TypeSpec/node_modules/@typespec/compiler/dist/src/core/install.js:4:19)
    at file:///D:/Scratch/TypeSpec/node_modules/@typespec/compiler/dist/src/core/cli/cli.js:157:95
    at Object.handler (file:///D:/Scratch/TypeSpec/node_modules/@typespec/compiler/dist/src/core/cli/utils.js:16:16)
    at file:///D:/Scratch/TypeSpec/node_modules/yargs/build/lib/command.js:206:54
    at maybeAsyncResult (file:///D:/Scratch/TypeSpec/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)
    at CommandInstance.handleValidationAndGetResult (file:///D:/Scratch/TypeSpec/node_modules/yargs/build/lib/command.js:205:25)
    at CommandInstance.applyMiddlewareAndGetResult (file:///D:/Scratch/TypeSpec/node_modules/yargs/build/lib/command.js:245:20)
    at CommandInstance.runCommand (file:///D:/Scratch/TypeSpec/node_modules/yargs/build/lib/command.js:128:20) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

It seems similar to an error mentioned here: https://blogs.namitoyokota.com/error-spawn-einval 

Could you please look into it and see if it will require similar resolution?

Edition	Windows 11 Pro
Version	23H2
Installed on	‎6/‎30/‎2023
OS build	22631.3527
Experience	Windows Feature Experience Pack 1000.22700.1003.0

### Reproduction

1. Create new directory
2. Execute `tsp init` with defaults (see Getting Started)
3. Execute `tsp install`

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DarekDan** [comment]
I have confirmed that manually adding `shell: true` resolved the problem. Will be submitting PR shortly.

**Comment by DarekDan** [comment]
No need for action. Issue related to https://github.com/microsoft/typespec/pull/3243
