### ISSUE TITLE
Specifying interface in operation props causes emitter to crash

### ISSUE THREAD

**Issue by shiron-dev** [microsoft/typespec#3504]
### Clear and concise description of the problem

When using “@typespec/openapi3”, specifying interface in operation props causes emitter to crash.
From a light reading of the implementation, it seems to me that it is not intended to specify an Interface in this ModelProperty section. In this case, why not make it an error message to the effect that “Interface cannot be specified in ModelProperty”?

Here is a simple example: both TestInterface1 and TestInterface2 generate the same error.
https://typespec.io/playground?c=aW50ZXJmYWNlIFRlc3RJyA4xIHsKICBnZXQxKHByb3A6zx4p0BE7Cn0KCtdMMiB7fQoKb3DETzLUTzLQTzI7Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D

Here is the current hard to understand error.
```
ExternalError: Emitter "@typespec/openapi3" crashed! This is a bug.
Please file an issue at https://github.com/microsoft/typespec/issues

Error: Unexpected non-code result from emit reference
    at OpenAPI3SchemaEmitter.modelPropertyLiteral (https://typespec.blob.core.windows.net/pkgs/@typespec/openapi3/0.56.0/index.js:3866:19)
    at https://typespec.blob.core.windows.net/pkgs/@typespec/compiler/0.56.0/emitter-utils-Bonv920s.js:17245:55
    at withTypeContext (https://typespec.blob.core.windows.net/pkgs/@typespec/compiler/0.56.0/emitter-utils-Bonv920s.js:17388:9)
    at invokeTypeEmitter (https://typespec.blob.core.windows.net/pkgs/@typespec/compiler/0.56.0/emitter-utils-Bonv920s.js:17235:9)
    at Object.emitModelProperty (https://typespec.blob.core.windows.net/pkgs/@typespec/compiler/0.56.0/emitter-utils-Bonv920s.js:17187:20)
    at OpenAPI3SchemaEmitter.modelProperties (https://typespec.blob.core.windows.net/pkgs/@typespec/openapi3/0.56.0/index.js:3825:41)
    at https://typespec.blob.core.windows.net/pkgs/@typespec/compiler/0.56.0/emitter-utils-Bonv920s.js:17245:55
    at withTypeContext (https://typespec.blob.core.windows.net/pkgs/@typespec/compiler/0.56.0/emitter-utils-Bonv920s.js:17388:9)
    at invokeTypeEmitter (https://typespec.blob.core.windows.net/pkgs/@typespec/compiler/0.56.0/emitter-utils-Bonv920s.js:17235:9)
    at Object.emitModelProperties (https://typespec.blob.core.windows.net/pkgs/@typespec/compiler/0.56.0/emitter-utils-Bonv920s.js:17178:25)

```

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by timotheeguerin** [comment]
This shouldn't crash but what would you expect this to do?

**Comment by markcowl** [comment]
- consider handling this in the emitter framework when operations are processed

**Comment by shiron-dev** [comment]
I want the error to be output in the following form. Note that the content of the message is tentative.

```
/Users/user/projects/typespec/packages/samples/scratch/main.tsp:7:9 - error @typespec/openapi3/model-property-non-code-result: 'Interface' cannot be specified in ModelProperty.
> 7 | op get2(prop: TestInterface2): TestInterface2;
    |         ^^^^
/Users/user/projects/typespec/packages/samples/scratch/main.tsp:2:8 - error @typespec/openapi3/model-property-non-code-result: 'Interface' cannot be specified in ModelProperty.
> 2 |   get1(prop: TestInterface1): TestInterface1;
    |        ^^^^

Found 2 errors.
```

This was reproduced by calling `reportDiagnostic` on the part that throws the original error (“Unexpected non-code result from emit reference”).
If you are okay with this policy, please let me create a PR.

**Comment by timotheeguerin** [comment]
yep that's exactly what I would expect to happen, I was just wondering if you were expecting this to produce some OpenAPI3 output.
Looking forward to the PR
