### ISSUE TITLE
[Bug]: `Error: spawnSync npm.cmd EINVAL` when `tsp code install`

### ISSUE THREAD

**Issue by archerzz** [microsoft/typespec#3513]
### Describe the bug

The follow error shows up when executing `tsp code install`:
```
PS C:\Users\xxx> tsp code install
TypeSpec compiler v0.56.0

tsp code install

Install VS Code Extension

Options:
  --help      Show help                                                [boolean]
  --debug     Output debug log messages.              [boolean] [default: false]
  --pretty    Enable color and formatting in TypeSpec's output to make compiler
              errors easier to read.                   [boolean] [default: true]
  --version   Show version number                                      [boolean]
  --insiders  Use VS Code Insiders                    [boolean] [default: false]

Error: spawnSync npm.cmd EINVAL
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:876:24)
    at run (file:///C:/Users/xxx/AppData/Roaming/npm/node_modules/@typespec/compiler/dist/src/core/cli/utils.js:59:18)
    at installVsix (file:///C:/Users/xxx/AppData/Roaming/npm/node_modules/@typespec/compiler/dist/src/core/cli/install-vsix.js:24:5)
    at async installVSCodeExtension (file:///C:/Users/xxx/AppData/Roaming/npm/node_modules/@typespec/compiler/dist/src/core/cli/actions/vscode.js:6:12)
    at async Object.handler (file:///C:/Users/xxx/AppData/Roaming/npm/node_modules/@typespec/compiler/dist/src/core/cli/utils.js:25:29) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawnSync npm.cmd',
  path: 'npm.cmd',
  spawnargs: [ 'install', '--silent', '--prefix', '.', 'typespec-vscode' ]
}
```

---

I checked https://github.com/microsoft/typespec/pull/3243 which fixed a similar issue. But the corresponding issue #3242 has different error stack.

Checking the source codes, looks like we need to add `"shell": true` here: https://github.com/microsoft/typespec/blob/5da8fe78d4b3e4000b96cdc5dfd12ee88532aa7b/packages/compiler/src/core/cli/utils.ts#L92 Probably we need to add a property in [RunOptions](https://github.com/microsoft/typespec/blob/5da8fe78d4b3e4000b96cdc5dfd12ee88532aa7b/packages/compiler/src/core/cli/utils.ts#L18)

### Reproduction

Use a brand new windows environment. Install typespec 0.56, follow the doc to install vs code plugin.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Environment

- TypeSpec `0.56.0`
- Node v20.14.0
- OS: Windows 11 enterprise

**Comment by pshao25** [comment]
I met same problem when running `rush format` for autorest in a devbox.

at Object.spawnSync (node:internal/child_process:1117:20)
at spawnSync (node:child_process:876:24)
at run (C:\Users\xxx\GIT\autorest\eng\scripts\helpers.js:26:50)
at runPrettier (C:\Users\xxx\GIT\autorest\eng\scripts\helpers.js:48:3)
at Object.<anonymous> (C:\Users\xxx\GIT\autorest\eng\scripts\format.js:2:1)
at Module._compile (node:internal/modules/cjs/loader:1364:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
at Module.load (node:internal/modules/cjs/loader:1203:32)
at Module._load (node:internal/modules/cjs/loader:1019:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {

**Comment by timotheeguerin** [comment]
Seems like a bug but any reason to install via the command line and not the extension in the marketplace?

**Comment by archerzz** [comment]
> Seems like a bug but any reason to install via the command line and not the extension in the marketplace?

I get used to run on command line, so when I saw the [`Installation` section of readme](https://github.com/microsoft/typespec#installation), I just copied & pasted `tsp code install`.
