### ISSUE TITLE
Update emitter to change Parent on InputClient from a string to an InputClient

### ISSUE THREAD

**Issue by nisha-bhatia** [microsoft/typespec#4326]
When working on this issue [#3969](https://github.com/microsoft/typespec/issues/3969), I found a bug in RestClientProvider.cs where paramMap doesn't get populated with all the UriParameters. The solution is to modify the emitter by updating InputClient.Parent from string to a full InputClient so the parameters can get passed on to the Child clients. After this update, the RenameOperation work item can be completed.

![Image](https://github.com/user-attachments/assets/5ffb199d-ccb1-47c1-b740-689295d6bbbe)

Error below:
The given key 'apiVersion' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Generator.CSharp.ClientModel.Providers.RestClientProvider.GetParamInfo(Dictionary`2 paramMap, InputParameter inputParam, CSharpType& type, String& format, ValueExpression& valueExpression)
   at Microsoft.Generator.CSharp.ClientModel.Providers.RestClientProvider.AppendQueryParameters(ScopedApi`1 uri, InputOperation operation, Dictionary`2 paramMap)
   at Microsoft.Generator.CSharp.ClientModel.Providers.RestClientProvider.BuildCreateRequestMethod(InputOperation operation)
   at Microsoft.Generator.CSharp.ClientModel.Providers.RestClientProvider.BuildMethods()
   at Microsoft.Generator.CSharp.Providers.TypeProvider.get_Methods()
   at Microsoft.Generator.CSharp.ClientModel.Providers.RestClientProvider.GetCreateRequestMethod(InputOperation operation)
   at Microsoft.Generator.CSharp.ClientModel.Providers.ScmMethodProviderCollection..ctor(InputOperation operation, TypeProvider enclosingType)
   at Microsoft.Generator.CSharp.ClientModel.ScmTypeFactory.CreateMethods(InputOperation operation, TypeProvider enclosingType)
   at Microsoft.Generator.CSharp.ClientModel.Providers.ClientProvider.BuildMethods()
   at Microsoft.Generator.CSharp.Providers.TypeProvider.get_Methods()

**Comment by m-nash** [comment]
@nisha-bhatia is this complete?  If so can you close it?
