### ISSUE TITLE
[Bug]: Client python expect some properties to be defined in the tsp config and crash if they are not

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#4723]
### Describe the bug

```
Emitter "@typespec/http-client-python" crashed! This is a bug.
Please file an issue at https://github.com/microsoft/typespec/issues

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at addDefaultOptions (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/http-client-python/emitter/src/emitter.ts:48:43)
    at Object.$onEmit [as emitFunction] (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/http-client-python/emitter/src/emitter.ts:81:3)
    at runEmitter (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/http-client-python/node_modules/@typespec/compiler/src/core/program.ts:578:7)
    at compile (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/http-client-python/node_modules/@typespec/compiler/src/core/program.ts:252:5)
    at compileOnce (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/http-client-python/node_modules/@typespec/compiler/src/core/cli/actions/compile/compile.ts:65:21)
    at compileAction (file:///Users/timotheeguerin/dev/azsdk/typespec/packages/http-client-python/node_modules/@typespec/compiler/src/core/cli/actions/compile/compile.ts:31:5)

--------------------------------------------------
Library Version                0.3.0
TypeSpec Compiler Version      0.61.0
--------------------------------------------------
```

1. It shoudln't crash
2. It shouldn't require the properties(don't require the user to fill in tons of config to get the emitter working)

### Reproduction

Run `tsp compile . --emit "@typespec/http-client-python"` in a simple `main.tsp` file without a tspconfig.yaml

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by msyyc** [comment]
Will take an investigation ASAP.

**Comment by msyyc** [comment]
Hi @timotheeguerin I can't reproduce the error locally. Could you try again with latest version? If the same error still occurs, please the `main.tsp` or the project which meets the crash issue. Thanks!

**Comment by msyyc** [comment]
I see. I can reproduce it with `main.tsp` that only has `model Foo {}`. Let me take an investigation.

**Comment by msyyc** [comment]
Python emitter bases on client/operation to generate SDK code, so if there is only model in .tsp file, the whole flow could not work. If it is common scenarios, Python emitter will make a fix for it.

**Comment by timotheeguerin** [comment]
The error doesn't reflect that at all, it is also unacceptable that you crash it is reported as a bug. If you don't support that you should emit diagnostic that can be understood. Plus having model only is something that has been asked many times. Maybe its not the job of this emitter but this common scenario.

**Comment by msyyc** [comment]
It is fixed in latest emitter version.
