### ISSUE TITLE
[Bug]: vscode: addon crashes (on windows?)

### ISSUE THREAD

**Issue by crowbait** [microsoft/typespec#5042]
### Describe the bug

The TypeSpec VSCode addon keeps crashing. 

![Image](https://github.com/user-attachments/assets/eddb3fac-a56a-4ea4-979a-0d2eba0d7278)

This excerpt from `package.json` shows that I'm using the latest versions of TSP packages:
```json
    "@typespec/compiler": "^0.62.0",
    "@typespec/http": "^0.62.0",
    "@typespec/json-schema": "^0.62.0",
    "@typespec/openapi3": "^0.62.0",
```

The addon itself is also on `v0.62.0`.

Log of VSCode addon:
```
2024-11-10 13:25:04.936 [error] Server initialization failed.
2024-11-10 13:25:04.937 [error]   Message: Pending response rejected since connection got disposed  Code: -32097 
2024-11-10 13:25:04.937 [info] Connection to server got closed. Server will restart.
2024-11-10 13:25:04.937 [info] true
2024-11-10 13:25:04.937 [error] TypeSpec client: couldn't create connection to server.
2024-11-10 13:25:04.937 [error]   Message: Pending response rejected since connection got disposed Code: -32097 
2024-11-10 13:25:04.946 [error] Server process exited with code 1.
2024-11-10 13:25:05.252 [error] 'tsp-server.cmd' is not recognized as an internal or external command, operable program or batch file.

[... repeats 2 times]

2024-11-10 13:25:06.340 [error] Client TypeSpec: connection to server is erroring.
write EPIPE
Shutting down server.
2024-11-10 13:25:06.341 [error] Stopping server failed
2024-11-10 13:25:06.341 [error] Error: Client is not running and can't be stopped. It's current state is: startFailed
	at LanguageClient.shutdown (c:\Users\[...]\.vscode\extensions\typespec.typespec-vscode-0.62.0\dist\src\extension.cjs:19372:20)
	at LanguageClient.stop (c:\Users\[...]\.vscode\extensions\typespec.typespec-vscode-0.62.0\dist\src\extension.cjs:19343:22)
	at LanguageClient.stop (c:\Users\[...]\.vscode\extensions\typespec.typespec-vscode-0.62.0\dist\src\extension.cjs:21887:24)
	at LanguageClient.handleConnectionError (c:\Users\[...]\.vscode\extensions\typespec.typespec-vscode-0.62.0\dist\src\extension.cjs:19604:19)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-11-10 13:25:06.341 [error] Server initialization failed.
2024-11-10 13:25:06.341 [error]   Message: write EPIPE Code: -32099 
2024-11-10 13:25:06.341 [error] TypeSpec client: couldn't create connection to server.
2024-11-10 13:25:06.341 [error]   Message: write EPIPE Code: -32099 
2024-11-10 13:25:06.342 [error] Restarting server failed
2024-11-10 13:25:06.342 [error]   Message: write EPIPE Code: -32099 
2024-11-10 13:25:06.342 [error] Restarting server failed
2024-11-10 13:25:06.342 [error]   Message: write EPIPE Code: -32099 
2024-11-10 13:25:06.342 [error] 'tsp-server.cmd' is not recognized as an internal or external command,
operable program or batch file.

[... repeats 1 time]

2024-11-10 13:25:06.519 [error] Server process exited with code 1.
2024-11-10 13:25:06.527 [error] The TypeSpec server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2024-11-10 13:25:13.246 [info] Providing tsp tasks
2024-11-10 13:25:13.309 [info] Found 1 main.tsp files
2024-11-10 13:25:13.318 [info] Provided 2 tsp tasks
```

### Reproduction

A freshly installed TSP project using the VSCode addon should have the same issues.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by RodgeFu** [comment]
@crowbait , I tried to use 0.62 compiler and vscode extension, but can't get the repro. From the log, it seems that vscode extension can't find the "tsp-server.cmd" file. Could you help to confirm whether you have the compiler installed properly in your node_modules folder? or globally?

If the compiler installed properly, could you send us following information so that we can do further investigation? thanks.
1. the file structure in your project.
2. The settings of "tsp-server" if you have set it.
3. Send us more detail logs by setting the LogLevel in vscode to "Debug" (you can change the loglevel by "Set Log Level..." command). thanks.

**Comment by crowbait** [comment]
> From the log, it seems that vscode extension can't find the "tsp-server.cmd" file. Could you help to confirm whether you have the compiler installed properly in your node_modules folder? or globally?

After having a good long look at things, I figured out the issue.

First of all, I'm working in a monorepo; the API (which I use TypeSpec to describe) is one subdirectory of the repo, not on the top level. So my TSP installation was not in `{workspace}/node_modules` but `{workspace}/api/node_modules`. So it makes sense it couldn't load if it was looking in the wrong place.
Interestingly, everything *had* worked before, just about until 0.62 ...

So, setting the path in the addon's settings to `${workspaceFolder}/api/node_modules/@typespec/compiler` worked fine and my addon is running again.
Best moment to say "thank you for your input"!

However, this would have been a *lot* easier to resolve, if the addon would log which executable (`tsp-server.cmd`) it will now attempt to load - by default. Finding the log and looking through it is easy - vscode helpfully offers that when the addon crashes. But switching the log level is at least somewhat more obscure. So maybe you could adding critical information like that to the default log level?

Anyways, again: thank you for the input and I'm glad stuff's working again.

**Comment by RodgeFu** [comment]
Glad to know that the issue is resolved and thank you for the suggestion. We will improve the log for that part. thanks.
