### ISSUE TITLE
[Bug]: Error: Emit context must have a scope set in order to create references to declarations.

### ISSUE THREAD

**Issue by brrusino** [microsoft/typespec#5077]
### Describe the bug

Hello,

We recently migrated from TypeSpec 0.55.0 to 0.62.0 and are seeing the following failure when trying use our existing (and previously working) json schema emitter implementation:
```
PS C:\Repos\Chaos\ARM-Gateway\temp\TypeSpec\2024-01-01> tsp compile main-wrapper.tsp --debug --no-emit
TypeSpec compiler v0.62.0

Emitter "@typespec/json-schema" crashed! This is a bug.
Please file an issue at https://github.com/microsoft/typespec/issues

Error: Emit context must have a scope set in order to create references to declarations.
    at compilerAssert (file:///C:/Repos/Chaos/ARM-Gateway/node_modules/@typespec/compiler/dist/src/core/diagnostics.js:169:11)
    at invokeReference (file:///C:/Repos/Chaos/ARM-Gateway/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:195:25)
    at file:///C:/Repos/Chaos/ARM-Gateway/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:183:28
    at withPatchedReferenceContext (file:///C:/Repos/Chaos/ARM-Gateway/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:540:20)
    at Object.emitTypeReference (file:///C:/Repos/Chaos/ARM-Gateway/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:144:20)
    at JsonSchemaEmitter.unionVariant (file:///C:/Repos/Chaos/ARM-Gateway/node_modules/@typespec/json-schema/dist/src/json-schema-emitter.js:210:42)
    at file:///C:/Repos/Chaos/ARM-Gateway/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:377:55
    at withTypeContext (file:///C:/Repos/Chaos/ARM-Gateway/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:520:9)
    at invokeTypeEmitter (file:///C:/Repos/Chaos/ARM-Gateway/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:367:9)
    at Object.emitType (file:///C:/Repos/Chaos/ARM-Gateway/node_modules/@typespec/compiler/dist/src/emitter-framework/asset-emitter.js:268:28)
```

### Reproduction

tspconfig is as follows:
```
emit:
  - "@typespec/json-schema"
options:
  "@typespec/json-schema":
    file-type: "json"
    emitAllModels: false
    emitAllRefs: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
```

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chrisradek** [comment]
I was able to create a simple repro:
[Playground](https://typespec.io/playground/?c=aW1wb3J0ICJAdHlwZXNwZWMvanNvbi1zY2hlbWEiOwoKdXNpbmcgVHlwZVNwZWMuSnNvblPFHTsKCkDELMYOCm5hbWVzcGFjZSBFeGFtcGxlOwoKbW9kZWwgRm9vIHsKICAuLi5TcHJlYWRNZTsKICAvLyBIb3dldmVyLCBtYW51YWxseSB3cml0xHB0aGUgc8UtIHdvcmtzxjDkAKQ6IMhFLsQPCn3IZ8gXxWwvLyBUaGlzIHVuaW9uIGluxVFyZWNvcmQgY3Jhc2hlxFPGUFLFFzxQdXRNZUluQcYPIHwgbnVsbD47ymHPIXt9Cg%3D%3D&e=%40typespec%2Fjson-schema&options=%7B%22options%22%3A%7B%22%40typespec%2Fjson-schema%22%3A%7B%22emitAllRefs%22%3Atrue%2C%22emitAllModels%22%3Afalse%7D%7D%7D)

This happens whether `emitAllModels` is true or false.

Something about spreading a model that contains a Record instantiated with a union where one of the variants is a model reference.

Not using the spread makes the issue go away.

This is seen in the wild with usage of Azure.ResourceManager.ManagedServiceIdentityProperty

**Comment by chrisradek** [comment]
Another note - I tested the simple repro with `@typespec/compiler` and `@typespec/json-schema` version 0.55.0 and they encounter the same issue - so I suspect there were changes to some other TypeSpec libraries that now exercise this problem scenario.
