### ISSUE TITLE
[http-server-javascript] server gen for js crashes because of invalid identifier

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#5185]
Please run `tsp compile ./petstore/spec` on [this PR](https://github.com/allenjzhang/typespec-e2e-demo/pull/5) to reproduce this.

Here is the stack trace:
```
SyntaxError: Identifier expected. (75:15)
  73 |   );
  74 |
> 75 |   if ((result.) === (200)) {
     |               ^
  76 |     response.statusCode = result.;
  77 |     delete (result as any).;
  78 |     response.end();
    at Q4 (file:///C:/Users/dapzhang/Documents/workspace/typespec-e2e-demo/node_modules/prettier/plugins/typescript.mjs:17:76108)
    at x3 (file:///C:/Users/dapzhang/Documents/workspace/typespec-e2e-demo/node_modules/prettier/plugins/typescript.mjs:20:773)
    at Object.w3 [as parse] (file:///C:/Users/dapzhang/Documents/workspace/typespec-e2e-demo/node_modules/prettier/plugins/typescript.mjs:20:1164)
    at parse4 (file:///C:/Users/dapzhang/Documents/workspace/typespec-e2e-demo/node_modules/prettier/index.mjs:20685:24)
    at async coreFormat (file:///C:/Users/dapzhang/Documents/workspace/typespec-e2e-demo/node_modules/prettier/index.mjs:21146:7)
    at async formatWithCursor (file:///C:/Users/dapzhang/Documents/workspace/typespec-e2e-demo/node_modules/prettier/index.mjs:21348:14)
    at async Module.format2 (file:///C:/Users/dapzhang/Documents/workspace/typespec-e2e-demo/node_modules/prettier/index.mjs:22733:25)
    at async writeModuleFile (file:///C:/Users/dapzhang/Documents/workspace/typespec-e2e-demo/node_modules/@typespec/http-server-javascript/dist/src/write.js:52:11)
    at async writeModuleTree (file:///C:/Users/dapzhang/Documents/workspace/typespec-e2e-demo/node_modules/@typespec/http-server-javascript/dist/src/write.js:23:9)
    at async Object.$onEmit [as emitFunction] (file:///C:/Users/dapzhang/Documents/workspace/typespec-e2e-demo/node_modules/@typespec/http-server-javascript/dist/src/index.js:83:9)
```
actually something is generated but I did not find this in any generated file.

**Comment by witemple-msft** [comment]
Thanks for the report. Will be fixed and closed in #5188 that handles "unspeakable" identifiers like `_` when they are used for protocol metadata like `@statusCode`
