### ISSUE TITLE
[Bug]: When main.tsp only contain minimal import, emitter fails

### ISSUE THREAD

**Issue by allenjzhang** [microsoft/typespec#5419]
### Describe the bug

Right after `tsp init` with empty project that only, `npx tsp compile .` fails.

```
Emitter "@typespec/http-client-csharp" crashed! This is a bug.
Please file an issue at https://github.com/Microsoft/typespec/issues

Error: Root client not found
    at getRootApiVersions (file:///C:/github/typespec-e2e-demo/sandbox/junk/node_modules/@typespec/http-client-csharp/dist/emitter/lib/client-model-builder.js:130:15)
    at createModel (file:///C:/github/typespec-e2e-demo/sandbox/junk/node_modules/@typespec/http-client-csharp/dist/emitter/lib/client-model-builder.js:23:11)
    at Object.$onEmit [as emitFunction] (file:///C:/github/typespec-e2e-demo/sandbox/junk/node_modules/@typespec/http-client-csharp/dist/emitter/emitter.js:44:22)
    at async runEmitter (file:///C:/github/typespec-e2e-demo/sandbox/junk/node_modules/@typespec/compiler/dist/src/core/program.js:366:13)
    at async compile (file:///C:/github/typespec-e2e-demo/sandbox/junk/node_modules/@typespec/compiler/dist/src/core/program.js:123:9)
    at async compileOnce (file:///C:/github/typespec-e2e-demo/sandbox/junk/node_modules/@typespec/compiler/dist/src/core/cli/actions/compile/compile.js:36:25)
    at async compileAction (file:///C:/github/typespec-e2e-demo/sandbox/junk/node_modules/@typespec/compiler/dist/src/core/cli/actions/compile/compile.js:19:9)
```

main.tsp only contains following:
```
import "@typespec/http";
import "@typespec/rest";
import "@typespec/openapi3";
```

### Reproduction

In E2E repo, 

```bash
cd sandbox
md [project] && cd [project]
npx tsp init ../../tsptemplate.json
npm install
npx tsp compile .
```

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ArthurMa1978** [comment]
We should verify if this issue exists in other languages too.

**Comment by rs-jayanth** [comment]
http-client-java compiles, but csharp and python client doesn't.  There's an open issue - [5363](https://github.com/microsoft/typespec/issues/5363)

**Comment by msyyc** [comment]
Already fixed by https://github.com/microsoft/typespec/pull/5200 so please try latest https://www.npmjs.com/package/@typespec/http-client-python.

**Comment by allenjzhang** [comment]
The call stack is the one I would like to remove. It looked like an uncaught exception. 

I tried with latest build, the result looks fine to me now with one line error: 

`Cannot generate CSharp SDK since no public root client is defined in typeSpec file.`

BTW, nit, typespec should be TypeSpec. Once that fixed, you can close this issue. Thx

**Comment by JoshLove-msft** [comment]
> Cannot generate CSharp SDK since no public root client is defined in typeSpec file.

Probably should be "C# library" and "TypeSpec". We should follow up to find out what PR actually fixed this as it still should have been part of our triage process.

**Comment by JoshLove-msft** [comment]
This was fixed in https://github.com/microsoft/typespec/pull/5475

**Comment by m-nash** [comment]
I don't know if this was fixed would like to confirm with @allenjzhang what the expected result of an emitter should be if there are no clients or models in the spec?  Should we throw an error or should we generate an empty library?

@srnagar , @joheredi , @lmazuel how are your languages handling this?

**Comment by JoshLove-msft** [comment]
As a general rule, we should not be throwing for "known" error cases. These should instead use error diagnostics. The only time we throw is for "unknown" cases.

**Comment by JoshLove-msft** [comment]
> BTW, nit, typespec should be TypeSpec. Once that fixed, you can close this issue. Thx

We should fix the casing. But we need to have a Spector test that provides an empty TypeSpec and what the expectation is for this case. Right now, languages are doing different things.

**Comment by JoshLove-msft** [comment]
Adding Spector label since we need a spector scenario for an empty Typespec along with the expectations.
